/*
 * NeuralLog API
 * API documentation for the NeuralLog server
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.neurallog.sdk.api;

import com.neurallog.sdk.client.ApiClient;
import com.neurallog.sdk.client.ApiException;
import com.neurallog.sdk.client.ApiResponse;
import com.neurallog.sdk.client.Pair;

import com.neurallog.sdk.model.LogsLogNameDelete200Response;
import com.neurallog.sdk.model.LogsLogNameLogIdGet200Response;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class LogEntriesApi {
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<String>> memberVarAsyncResponseInterceptor;

  public LogEntriesApi() {
    this(new ApiClient());
  }

  public LogEntriesApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }

  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    String body = response.body() == null ? null : new String(response.body().readAllBytes());
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Delete a log entry by ID
   * 
   * @param logName Name of the log (required)
   * @param logId ID of the log entry (required)
   * @param namespace Namespace for the log (optional, default to default)
   * @return LogsLogNameDelete200Response
   * @throws ApiException if fails to make API call
   */
  public LogsLogNameDelete200Response logsLogNameLogIdDelete(String logName, String logId, String namespace) throws ApiException {
    ApiResponse<LogsLogNameDelete200Response> localVarResponse = logsLogNameLogIdDeleteWithHttpInfo(logName, logId, namespace);
    return localVarResponse.getData();
  }

  /**
   * Delete a log entry by ID
   * 
   * @param logName Name of the log (required)
   * @param logId ID of the log entry (required)
   * @param namespace Namespace for the log (optional, default to default)
   * @return ApiResponse&lt;LogsLogNameDelete200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<LogsLogNameDelete200Response> logsLogNameLogIdDeleteWithHttpInfo(String logName, String logId, String namespace) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = logsLogNameLogIdDeleteRequestBuilder(logName, logId, namespace);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("logsLogNameLogIdDelete", localVarResponse);
        }
        return new ApiResponse<LogsLogNameDelete200Response>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<LogsLogNameDelete200Response>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder logsLogNameLogIdDeleteRequestBuilder(String logName, String logId, String namespace) throws ApiException {
    // verify the required parameter 'logName' is set
    if (logName == null) {
      throw new ApiException(400, "Missing the required parameter 'logName' when calling logsLogNameLogIdDelete");
    }
    // verify the required parameter 'logId' is set
    if (logId == null) {
      throw new ApiException(400, "Missing the required parameter 'logId' when calling logsLogNameLogIdDelete");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/logs/{logName}/{logId}"
        .replace("{logName}", ApiClient.urlEncode(logName.toString()))
        .replace("{logId}", ApiClient.urlEncode(logId.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "namespace";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("namespace", namespace));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }
  /**
   * Get a log entry by ID
   * 
   * @param logName Name of the log (required)
   * @param logId ID of the log entry (required)
   * @param namespace Namespace for the log (optional, default to default)
   * @return LogsLogNameLogIdGet200Response
   * @throws ApiException if fails to make API call
   */
  public LogsLogNameLogIdGet200Response logsLogNameLogIdGet(String logName, String logId, String namespace) throws ApiException {
    ApiResponse<LogsLogNameLogIdGet200Response> localVarResponse = logsLogNameLogIdGetWithHttpInfo(logName, logId, namespace);
    return localVarResponse.getData();
  }

  /**
   * Get a log entry by ID
   * 
   * @param logName Name of the log (required)
   * @param logId ID of the log entry (required)
   * @param namespace Namespace for the log (optional, default to default)
   * @return ApiResponse&lt;LogsLogNameLogIdGet200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<LogsLogNameLogIdGet200Response> logsLogNameLogIdGetWithHttpInfo(String logName, String logId, String namespace) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = logsLogNameLogIdGetRequestBuilder(logName, logId, namespace);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("logsLogNameLogIdGet", localVarResponse);
        }
        return new ApiResponse<LogsLogNameLogIdGet200Response>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<LogsLogNameLogIdGet200Response>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder logsLogNameLogIdGetRequestBuilder(String logName, String logId, String namespace) throws ApiException {
    // verify the required parameter 'logName' is set
    if (logName == null) {
      throw new ApiException(400, "Missing the required parameter 'logName' when calling logsLogNameLogIdGet");
    }
    // verify the required parameter 'logId' is set
    if (logId == null) {
      throw new ApiException(400, "Missing the required parameter 'logId' when calling logsLogNameLogIdGet");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/logs/{logName}/{logId}"
        .replace("{logName}", ApiClient.urlEncode(logName.toString()))
        .replace("{logId}", ApiClient.urlEncode(logId.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "namespace";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("namespace", namespace));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }
  /**
   * Update a log entry by ID
   * 
   * @param logName Name of the log (required)
   * @param logId ID of the log entry (required)
   * @param body  (required)
   * @param namespace Namespace for the log (optional, default to default)
   * @return LogsLogNameDelete200Response
   * @throws ApiException if fails to make API call
   */
  public LogsLogNameDelete200Response logsLogNameLogIdPost(String logName, String logId, Object body, String namespace) throws ApiException {
    ApiResponse<LogsLogNameDelete200Response> localVarResponse = logsLogNameLogIdPostWithHttpInfo(logName, logId, body, namespace);
    return localVarResponse.getData();
  }

  /**
   * Update a log entry by ID
   * 
   * @param logName Name of the log (required)
   * @param logId ID of the log entry (required)
   * @param body  (required)
   * @param namespace Namespace for the log (optional, default to default)
   * @return ApiResponse&lt;LogsLogNameDelete200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<LogsLogNameDelete200Response> logsLogNameLogIdPostWithHttpInfo(String logName, String logId, Object body, String namespace) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = logsLogNameLogIdPostRequestBuilder(logName, logId, body, namespace);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("logsLogNameLogIdPost", localVarResponse);
        }
        return new ApiResponse<LogsLogNameDelete200Response>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<LogsLogNameDelete200Response>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder logsLogNameLogIdPostRequestBuilder(String logName, String logId, Object body, String namespace) throws ApiException {
    // verify the required parameter 'logName' is set
    if (logName == null) {
      throw new ApiException(400, "Missing the required parameter 'logName' when calling logsLogNameLogIdPost");
    }
    // verify the required parameter 'logId' is set
    if (logId == null) {
      throw new ApiException(400, "Missing the required parameter 'logId' when calling logsLogNameLogIdPost");
    }
    // verify the required parameter 'body' is set
    if (body == null) {
      throw new ApiException(400, "Missing the required parameter 'body' when calling logsLogNameLogIdPost");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/logs/{logName}/{logId}"
        .replace("{logName}", ApiClient.urlEncode(logName.toString()))
        .replace("{logId}", ApiClient.urlEncode(logId.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "namespace";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("namespace", namespace));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(body);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }
}
