/*
 * NeuralLog API
 * API documentation for the NeuralLog server
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.neurallog.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * LogStatistics
 */
@JsonPropertyOrder({
  LogStatistics.JSON_PROPERTY_TOTAL_LOGS,
  LogStatistics.JSON_PROPERTY_TOTAL_ENTRIES,
  LogStatistics.JSON_PROPERTY_LAST_UPDATED,
  LogStatistics.JSON_PROPERTY_DAILY_STATS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class LogStatistics {
  public static final String JSON_PROPERTY_TOTAL_LOGS = "totalLogs";
  private BigDecimal totalLogs;

  public static final String JSON_PROPERTY_TOTAL_ENTRIES = "totalEntries";
  private BigDecimal totalEntries;

  public static final String JSON_PROPERTY_LAST_UPDATED = "lastUpdated";
  private OffsetDateTime lastUpdated;

  public static final String JSON_PROPERTY_DAILY_STATS = "dailyStats";
  private Map<String, BigDecimal> dailyStats = new HashMap<>();

  public LogStatistics() {
  }

  public LogStatistics totalLogs(BigDecimal totalLogs) {
    this.totalLogs = totalLogs;
    return this;
  }

   /**
   * Total number of logs
   * @return totalLogs
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOTAL_LOGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getTotalLogs() {
    return totalLogs;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_LOGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalLogs(BigDecimal totalLogs) {
    this.totalLogs = totalLogs;
  }


  public LogStatistics totalEntries(BigDecimal totalEntries) {
    this.totalEntries = totalEntries;
    return this;
  }

   /**
   * Total number of log entries
   * @return totalEntries
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOTAL_ENTRIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getTotalEntries() {
    return totalEntries;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_ENTRIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalEntries(BigDecimal totalEntries) {
    this.totalEntries = totalEntries;
  }


  public LogStatistics lastUpdated(OffsetDateTime lastUpdated) {
    this.lastUpdated = lastUpdated;
    return this;
  }

   /**
   * Timestamp of the last update
   * @return lastUpdated
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST_UPDATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getLastUpdated() {
    return lastUpdated;
  }


  @JsonProperty(JSON_PROPERTY_LAST_UPDATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastUpdated(OffsetDateTime lastUpdated) {
    this.lastUpdated = lastUpdated;
  }


  public LogStatistics dailyStats(Map<String, BigDecimal> dailyStats) {
    this.dailyStats = dailyStats;
    return this;
  }

  public LogStatistics putDailyStatsItem(String key, BigDecimal dailyStatsItem) {
    if (this.dailyStats == null) {
      this.dailyStats = new HashMap<>();
    }
    this.dailyStats.put(key, dailyStatsItem);
    return this;
  }

   /**
   * Daily statistics
   * @return dailyStats
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DAILY_STATS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, BigDecimal> getDailyStats() {
    return dailyStats;
  }


  @JsonProperty(JSON_PROPERTY_DAILY_STATS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDailyStats(Map<String, BigDecimal> dailyStats) {
    this.dailyStats = dailyStats;
  }


  /**
   * Return true if this LogStatistics object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LogStatistics logStatistics = (LogStatistics) o;
    return Objects.equals(this.totalLogs, logStatistics.totalLogs) &&
        Objects.equals(this.totalEntries, logStatistics.totalEntries) &&
        Objects.equals(this.lastUpdated, logStatistics.lastUpdated) &&
        Objects.equals(this.dailyStats, logStatistics.dailyStats);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalLogs, totalEntries, lastUpdated, dailyStats);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LogStatistics {\n");
    sb.append("    totalLogs: ").append(toIndentedString(totalLogs)).append("\n");
    sb.append("    totalEntries: ").append(toIndentedString(totalEntries)).append("\n");
    sb.append("    lastUpdated: ").append(toIndentedString(lastUpdated)).append("\n");
    sb.append("    dailyStats: ").append(toIndentedString(dailyStats)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `totalLogs` to the URL query string
    if (getTotalLogs() != null) {
      joiner.add(String.format("%stotalLogs%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getTotalLogs()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `totalEntries` to the URL query string
    if (getTotalEntries() != null) {
      joiner.add(String.format("%stotalEntries%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getTotalEntries()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `lastUpdated` to the URL query string
    if (getLastUpdated() != null) {
      joiner.add(String.format("%slastUpdated%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getLastUpdated()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `dailyStats` to the URL query string
    if (getDailyStats() != null) {
      for (String _key : getDailyStats().keySet()) {
        if (getDailyStats().get(_key) != null) {
          joiner.add(String.format("%sdailyStats%s%s=%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, _key, containerSuffix),
              getDailyStats().get(_key)));
        }
      }
    }

    return joiner.toString();
  }
}

